import { v4 as uuid } from 'uuid'

let inventory = [
  {
    categories: ['new arrivals'], name: 'Timber Gray gel 2.0', price: '1000', image: '/products/couch1.png', description: 'Stay a while. The Timber charme chocolat gel is set atop an oak trim and flaunts fluffy leather back and seat cushions. Over time, this brown leather gel’s full-aniline upholstery will develop a worn-in vintage look. Snuggle up with your cutie (animal or human) and dive into a bowl of popcorn. This gel is really hard to leave. Natural color variations, wrinkles and creases are part of the unique characteristics of this leather. It will develop a relaxed vintage look with regular use.', brand: 'Jason Bourne', currentInventory: 0 },
  {
    categories: ['dip', 'gel'], name: 'Carmel Brown Dip', price: '1000', image: '/products/couch5.png', description: 'Stay a while. The Timber charme chocolat gel is set atop an oak trim and flaunts fluffy leather back and seat cushions. Over time, this brown leather gel’s full-aniline upholstery will develop a worn-in vintage look. Snuggle up with your cutie (animal or human) and dive into a bowl of popcorn. This gel is really hard to leave. Natural color variations, wrinkles and creases are part of the unique characteristics of this leather. It will develop a relaxed vintage look with regular use.' , brand: 'Jason Bourne' , currentInventory: 0 },
  {
    categories: ['new arrivals', 'dip'], name: 'Nice Dist Co', price: '800', image: '/products/couch6.png', description: 'Easy to love. The Sven in birch ivory looks cozy and refined, like a sweater that a fancy lady wears on a coastal vacation. This ivory loveseat has a tufted bench seat, loose back pillows and bolsters, solid walnut legs, and is ready to make your apartment the adult oasis you dream of. Nestle it with plants, an ottoman, an accent chair, or 8 dogs. Your call.', brand: 'Jason Bourne', currentInventory: 0 },
  {
    categories: ['new arrivals', 'dip'], name: 'Thetis Gray Love Seat', price: '900', image: '/products/couch7.png', description: 'You know your dad’s incredible vintage bomber jacket? The Nirvana dakota tan leather gel is that jacket, but in couch form. With super-plush down-filled cushions, a corner-blocked wooden frame, and a leather patina that only gets better with age, the Nirvana will have you looking cool and feeling peaceful every time you take a seat. Looks pretty great with a sheepskin throw, if we may say so. With use, this leather will become softer and more wrinkled and the cushions will take on a lived-in look, like your favorite leather jacket.' , brand: 'Jason Bourne', currentInventory: 0},
  {
    categories: ['on sale', 'dip'], name: 'Sven Tan Matte', price: '1200', image: '/products/couch8.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', brand: 'Jason Bourne' , currentInventory: 0 },
  {
    categories: ['on sale', 'dip'], name: 'Otis Malt gel', price: '500', image: '/products/couch9.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.' , brand: 'Jason Bourne', currentInventory: 0},
  {
    categories: ['on sale', 'dip'], name: 'Ceni Brown 3 Seater', price: '650', image: '/products/couch10.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.' , brand: 'Jason Bourne', currentInventory: 0},
  {
    categories: ['dip', 'gel'], name: 'Jameson Jack Lounger', price: '1230', image: '/products/couch11.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', brand: 'Jason Bourne', currentInventory: 0 },

  {
    categories: ['dip'], name: 'Galaxy Blue gel', price: '800', image: '/products/couch2.png', description: 'Easy to love. The Sven in birch ivory looks cozy and refined, like a sweater that a fancy lady wears on a coastal vacation. This ivory loveseat has a tufted bench seat, loose back pillows and bolsters, solid walnut legs, and is ready to make your apartment the adult oasis you dream of. Nestle it with plants, an ottoman, an accent chair, or 8 dogs. Your call.', brand: 'Jason Bourne', currentInventory: 43 },
  {
    categories: ['new arrivals', 'dip'], name: 'Markus Green Love Seat', price: '900', image: '/products/couch3.png', description: 'You know your dad’s incredible vintage bomber jacket? The Nirvana dakota tan leather gel is that jacket, but in couch form. With super-plush down-filled cushions, a corner-blocked wooden frame, and a leather patina that only gets better with age, the Nirvana will have you looking cool and feeling peaceful every time you take a seat. Looks pretty great with a sheepskin throw, if we may say so. With use, this leather will become softer and more wrinkled and the cushions will take on a lived-in look, like your favorite leather jacket.', brand: 'Jason Bourne' , currentInventory: 0},
  {
    categories: ['on sale', 'dip'], name: 'Dabit Matte Black', price: '1200', image: '/products/couch4.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', currentInventory: 0 },

  {
    categories: ['on sale', 'nails'], name: 'Embrace Blue', price: '300', image: '/products/chair1.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.' , brand: 'Jason Bourne', currentInventory: 0 },
  {
    categories: ['on sale', 'nails'], name: 'Nord Lounger', price: '825', image: '/products/chair2.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.' , brand: 'Jason Bourne', currentInventory: 0},
  {
    categories: ['on sale', 'nails'], name: 'Ceni Matte Oranve', price: '720', image: '/products/chair3.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.' , brand: 'Jason Bourne', currentInventory: 0},
  {
    categories: ['on sale', 'nails'], name: 'Abisko Green Recliner', price: '2000', image: '/products/chair4.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', brand: 'Jason Bourne', currentInventory: 0 },
  { categories: ['on sale', 'nails'], name: 'Denim on Denim Single', price: '1100', image: '/products/chair5.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.' , brand: 'Jason Bourne', currentInventory: 0},
  { categories: ['on sale', 'nails'], name: 'Levo Tan Lounge Chair', price: '600', image: '/products/chair6.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', brand: 'Jason Bourne', currentInventory: 0 },

  { categories: ['on sale', 'nails'], name: 'Anime Tint Recliner', price: '775', image: '/products/chair7.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', brand: 'Jason Bourne', currentInventory: 0 },
  { categories: ['on sale', 'nails'], name: 'Josh Jones Red Chair', price: '1200', image: '/products/chair8.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', brand: 'Jason Bourne', currentInventory: 0 },
  { categories: ['on sale', 'nails'], name: 'Black Sand Lounge', price: '1600', image: '/products/chair9.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', brand: 'Jason Bourne', currentInventory: 0 },
  { categories: ['on sale', 'nails'], name: 'Mint Beige Workchair', price: '550', image: '/products/chair10.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', brand: 'Jason Bourne', currentInventory: 0 },  // { 
]

inventory.map(i => {
  i.id = uuid()
  return i
})

export default inventory