import { v4 as uuid } from 'uuid'

let inventory = [
  {
    categories: ['new arrivals'], name: 'Rose #5 Massage Oil', price: '1000', image: '/products/nice-logo.png', description: 'description', brand: 'Jason Bourne', currentInventory: 0 },
  {
    categories: ['dip', 'gel'], name: 'Lavender Massage Oil', price: '1000', image: '/products/nice-logo.png', description: 'description' , brand: 'Jason Bourne' , currentInventory: 0 },
  {
    categories: ['new arrivals', 'dip'], name: 'Dip Top', price: '800', image: '/products/nice-logo.png', description: 'description', brand: 'Jason Bourne', currentInventory: 0 },
  {
    categories: ['new arrivals', 'lotion'], name: 'Dip Base', price: '900', image: '/products/nice-logo.png', description: 'description' , brand: 'Jason Bourne', currentInventory: 0},
  {
    categories: ['on sale', 'oil'], name: 'Dip', price: '1200', image: '/products/nice-logo.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', brand: 'Jason Bourne' , currentInventory: 0 },
  {
    categories: ['on sale', 'dip'], name: 'Gel', price: '500', image: '/products/nice-logo.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.' , brand: 'Jason Bourne', currentInventory: 0},
  {
    categories: ['on sale', 'dip'], name: 'Gel', price: '650', image: '/products/nice-logo.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.' , brand: 'Jason Bourne', currentInventory: 0},
  {
    categories: ['dip', 'gel'], name: 'Oil', price: '1230', image: '/products/nice-logo.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', brand: 'Jason Bourne', currentInventory: 0 },

  {
    categories: ['dip'], name: 'Galaxy Blue gel', price: '800', image: '/products/nice-logo.png', description: 'Easy to love. The Sven in birch ivory looks cozy and refined, like a sweater that a fancy lady wears on a coastal vacation. This ivory loveseat has a tufted bench seat, loose back pillows and bolsters, solid walnut legs, and is ready to make your apartment the adult oasis you dream of. Nestle it with plants, an ottoman, an accent chair, or 8 dogs. Your call.', brand: 'Jason Bourne', currentInventory: 43 },
  {
    categories: ['new arrivals', 'dip'], name: 'dip', price: '900', image: '/products/nice-logo.png', description: 'You know your dad’s incredible vintage bomber jacket? The Nirvana dakota tan leather gel is that jacket, but in couch form. With super-plush down-filled cushions, a corner-blocked wooden frame, and a leather patina that only gets better with age, the Nirvana will have you looking cool and feeling peaceful every time you take a seat. Looks pretty great with a sheepskin throw, if we may say so. With use, this leather will become softer and more wrinkled and the cushions will take on a lived-in look, like your favorite leather jacket.', brand: 'Jason Bourne' , currentInventory: 0},
  {
    categories: ['on sale', 'dip'], name: 'dip Matte Black', price: '1200', image: '/products/nice-logo.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', currentInventory: 0 },

  {
    categories: ['on sale', 'lotion'], name: 'Gel Blue', price: '300', image: '/products/nice-logo.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.' , brand: 'Jason Bourne', currentInventory: 0 },
  {
    categories: ['on sale', 'nails'], name: 'Gel', price: '825', image: '/products/nice-logo.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.' , brand: 'Jason Bourne', currentInventory: 0},
  {
    categories: ['on sale', 'nails'], name: 'Gel', price: '720', image: '/products/nice-logo.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.' , brand: 'Jason Bourne', currentInventory: 0},
  {
    categories: ['on sale', 'nails'], name: 'Gel', price: '2000', image: '/products/nice-logo.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', brand: 'Jason Bourne', currentInventory: 0 },
  { categories: ['on sale', 'nails'], name: 'Gel', price: '1100', image: '/products/nice-logo.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.' , brand: 'Jason Bourne', currentInventory: 0},
  { categories: ['on sale', 'nails'], name: 'Gel', price: '600', image: '/products/nice-logo.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', brand: 'Jason Bourne', currentInventory: 0 },

  { categories: ['on sale', 'nails'], name: 'Gel', price: '775', image: '/products/nice-logo.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', brand: 'Jason Bourne', currentInventory: 0 },
  { categories: ['on sale', 'nails'], name: 'Gel', price: '1200', image: '/products/nice-logo.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', brand: 'Jason Bourne', currentInventory: 0 },
  { categories: ['on sale', 'nails'], name: 'Gel', price: '1600', image: '/products/nice-logo.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', brand: 'Jason Bourne', currentInventory: 0 },
  { categories: ['on sale', 'nails'], name: 'Gel', price: '550', image: '/products/nice-logo.png', description: 'You don’t have to go outside to be rugged. The Cigar rawhide gel features a sturdy corner-blocked wooden frame and raw seams for that Malboro-person look. This brown leather gel is cozy in a cottage, cabin, or a condo. And the leather (the leather!) becomes more beautiful with use: subtle character markings such as insect bites, healed scars, and grain variation reflects a real vintage. Saddle up and pass the remote.', brand: 'Jason Bourne', currentInventory: 0 },  // { 
]

inventory.map(i => {
  i.id = uuid()
  return i
})

export default inventory